Revert "Update puppetlabs/concat to 2.x"
This reverts commit 3f973fa24f82aeb4f4679fcbd4aa70e31812ab43.

Fixes the following error:

    Error: Could not install module 'puppetlabs-concat' (v2.0.1)
      No version of 'puppetlabs-concat' will satisfy dependencies
        You specified 'puppetlabs-concat' (v2.0.1)
        Use `puppet module install --force` to install this module anyway